spring:
  datasource:
    hikari:
      maximum-pool-size: 10  
      minimum-idle: 2
      connection-timeout: 30000
      
  jpa:
    show-sql: true 
    properties:
      "[hibernate.format_sql]": true  
      
  flyway:
    clean-disabled: false  

# Dev logging - verbose
logging:
  level:
    root: INFO
    "[com.moviereservation]": DEBUG  # Your app packages
    "[org.springframework.web]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.hibernate.SQL]": DEBUG  # SQL queries
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE  # SQL parameters
    "[org.hibernate.orm.jdbc.bind]": TRACE  # Parameter binding (Hibernate 6+)

# Dev server settings
server:
  error:
    include-stacktrace: always  # Always show stacktrace in dev

app:
  security:
    jwt:
      secret: e10b4cb4aa7672c002cfac3914025732aac97eccaf26c7db2e787245ebf80487
      expiration-ms: 86400000  # 1 day in milliseconds
  currency: INR
  stripe:
    api:
      secret-key: sk_test_51N1XXXXXX  # Replace with your Stripe test secret key
      public-key: pk_test_51N1XXXXXX  # Replace with your Stripe test public key
    webhook:
      secret: whsec_XXXXXXXXXXXXXXXXXXXX  # Replace with your Stripe webhook secret
