spring:
  application:
    name: movie-reservation-system  
  profiles:
    active: development

  # Common datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5432/mrs_db
    username: mrs_user
    password: mrs_password
    driver-class-name: org.postgresql.Driver
    
  # Common JPA settings
  jpa:
    hibernate:
      ddl-auto: none  
    open-in-view: false  
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.jdbc.time_zone]": UTC
      "[hibernate.jdbc.batch_size]": 20
      "[hibernate.order_inserts]": true
      "[hibernate.order_updates]": true
      
  # Common Flyway settings
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# Common server settings
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param  

# Common logging
logging:
  level:
    root: INFO
    "[com.moviereservation]": INFO