spring:
    datasource:
        hikari:
            maximum-pool-size: 20
            minimum-idle: 5
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            pool-name: MovieReservationCP
            leak-detection-threshold: 60000
            
    jpa:
        show-sql: false
        properties:
            "[hibernate.format_sql]": false
            "[hibernate.connection.provider_disables_autocommit]": true
            
    flyway:
        clean-disabled: true

logging:
    level:
        root: WARN
        "[com.moviereservation]": INFO
        "[org.springframework.web]": WARN
        "[org.springframework.security]": WARN
        "[org.hibernate.SQL]": WARN
    file:
        name: logs/movie-reservation.log
        max-size: 10MB
        max-history: 30

server:
    error:
        include-stacktrace: never
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain
    shutdown: graceful

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus
            base-path: /actuator
    endpoint:
        health:
            show-details: when-authorized
    prometheus:
        metrics:
            export:
                enabled: true
