spring:
  datasource:
    hikari:
      maximum-pool-size: 10  
      minimum-idle: 2
      connection-timeout: 30000
      
  jpa:
    show-sql: true 
    properties:
      "[hibernate.format_sql]": true  
      
  flyway:
    clean-disabled: false  

# Dev logging - verbose
logging:
  level:
    root: INFO
    "[com.moviereservation]": DEBUG  # Your app packages
    "[org.springframework.web]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.hibernate.SQL]": DEBUG  # SQL queries
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE  # SQL parameters
    "[org.hibernate.orm.jdbc.bind]": TRACE  # Parameter binding (Hibernate 6+)

# Dev server settings
server:
  error:
    include-stacktrace: always  # Always show stacktrace in dev

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-ms: 86400000  # 1 day in milliseconds
  currency: INR
  stripe:
    api:
      secret-key: ${STRIPE_API_SECRET_KEY}
      public-key: ${STRIPE_API_PUBLIC_KEY}  
    webhook:
      secret: ${STRIPE_WEBHOOK_SECRET}  
